### ISSUE TITLE
Referencing pages by name rather than path

### ISSUE THREAD

**Issue by phildini** [beeware/beeware.github.io#145]
Sometimes the location of pages in pybee.org change, and so the links break.

If lektor has the ability to refer to a page by name instead of path, they might break less!

This ticket is: investigate if lektor has this ability, and if so start adding it to our docs here.

**Comment by li3n3** [comment]
I will take this on!

**Comment by uranusjr** [comment]
From what I know Lektor actually is built heavily around using paths to identify contents. If a pages changes location, the user should provide proper redirection or explicitly changes all paths. Lektor simply treat the moved page as a new one.

What should be done, on the other hand, is to properly use [the `|url` and `|asseturl` filters](https://www.getlektor.com/docs/templates/urls/#url-filter) on paths, so they link correctly across alternatives. I’m trying to fix those raw URLs right now…

**Comment by goanpeca** [comment]
@uranusjr I think I covered all (unless I forgot something) with the latest PR for adding databags and localization.

Urls/paths inside rst content on the other hand have to be adapted on translation

**Comment by uranusjr** [comment]
@goanpeca Yes, I pulled the source after seeing this issue to work on it, only to find you already did all the hard work. Great job!

I wonder if we can extend Lektor’s rst renderer to make in-content path formatting easier. I did something similar for Markdown in a private CMS project before. Not sure if it’s worth the effort though.

**Comment by goanpeca** [comment]
I would say it is based on all thw urls within rst i have seen

**Comment by goanpeca** [comment]
@phildini in the mean time I wrote a script to check for broken links on the whole built site. We could even add this as a beekeeper job so that no links are left dead. On this issue I found that some links that refer to pycon asutralia in previous years no longer exist, but this is a different issues.

**Comment by freakboy3742** [comment]
Looks like this should be done as part of @goanpeca's changes.
