### ISSUE TITLE
Update readme (lektor version)

### ISSUE THREAD

**Issue by goanpeca** [beeware/beeware.github.io#156]
Lektor at least for linux/osx) is python3 ready. For windows python 3 still has some bugs and tests that fail.

Still, maybe we can update this

>If you want to test out a change before you submit it, download and install Lektor (note that Lektor is still using Python 2.7):
>$ pip install lektor

And also I would like to ask if it is possible to include a conda option (disclaimer, I built/maintain the Lektor conda-forge packages). Its fine if you guys don't agree. Lektor conda pakcages include a patch for windows and python3 (but I have not tested it deeply)

```
$ conda install lektor
```

**Comment by shreyateeza** [comment]
Hey I am new here. I would like to work on this issue.

**Comment by freakboy3742** [comment]
@shreyateeza Sure - dive right in! Essentially we need someone to verify that a Python3 configuration works; and if it does, update our Travis configuration and documentation to reflect this fact.

That said - if you're looking for ways to contribute, this possibly isn't the best place to start. Our [guide for new contributors](https://pybee.org/contributing/how/first-time/) has a collection of other projects that would be better suited to first-time contributors.

**Comment by goanpeca** [comment]
Actually @freakboy3742 there are still some glitches for python3 when making the deploy so, master has the solution in, but a new version has not been released yet, so I would put this on hold at the moment

**Comment by DholakiaJaydeep** [comment]
Hey, @freakboy3742 I just tested it in Python3 on Windows platform and it had many errors and exceptions showing. I have solved it! it now runs in Python3 and in Windows platform.

![lector running](https://user-images.githubusercontent.com/14180227/37973354-eb63661e-31f7-11e8-9776-4889856c9763.jpg)

**Comment by freakboy3742** [comment]
We've now migrated to Python3, and the README has been updated to reflect this.
