### ISSUE TITLE
beeware.org

### ISSUE THREAD

**Issue by afs2015** [beeware/beeware.github.io#281]
Based on a conversation with @freakboy3742 this ticket is to go through the sitemap of pybee.org and identify which pages should belong to new subdomains such as docs.beeware.org, contribute.beeware.org, etc.

[Here's a picture](https://imgur.com/a/aZwcQ8A) of the white board outlining the design with subdomains.

**Comment by afs2015** [comment]
Here's a pastebin of my first pass at breaking up the current sitemap.xml into different sections for beeware.org. Any feedback is appreciated!

https://pastebin.com/wWShwJfF

**Comment by freakboy3742** [comment]
Closing due to a lack of activity. A site redesign is still on the cards.
