### ISSUE TITLE
Bugs in the website menu

### ISSUE THREAD

**Issue by AltoRetrato** [beeware/beeware.github.io#292]
I noticed a couple of bugs on the website menu:

- The menu position is fixed, so it can't be scrolled (possibly hiding bottom items, specially in landscape mode)
- I can't change to another language due to the dropdown menu opening mostly out of the bottom of the screen

In the screenshot below (captured on Google Chrome, in "responsive" mode), you can see how the menu is visible in portrait mode and how the language selection menu is not accessible (at least on Google Chrome):

![clipboard01](https://user-images.githubusercontent.com/22997468/42544670-7dcae912-8489-11e8-9d89-96938f537cfc.png)

**Comment by pythoniseasy-hub** [comment]
Sir i Fixed This Issue
https://github.com/beeware/beeware.github.io/pull/454/files

**Comment by dhawal-kamdar** [comment]
I have fixed this issue.
Please check https://github.com/beeware/beeware.github.io/pull/459
or check live website https://deploy-preview-459--beeware.netlify.app/
