### ISSUE TITLE
Document translation of content in templates using databags

### ISSUE THREAD

**Issue by goanpeca** [beeware/beeware.github.io#300]
https://pybee.org/contributing/how/translations/

See [Lektor Docs](https://www.getlektor.com/docs/api/databags) and [this file](https://github.com/pybee/pybee.github.io/blob/lektor/databags/translate.ini

**Comment by freakboy3742** [comment]
We've added *some* content; closing on that basis. If anyone wants to improve on what is there, we can handle that with PRs.
