### ISSUE TITLE
RTL languages

### ISSUE THREAD

**Issue by Fcmam5** [beeware/beeware.github.io#313]
Arabic for example, is written from right-to-left, 

This is wrong, and sometimes it's hard to read for an Arab user, like it will be `email@domain.com for more information contact`.

![screenshot from 2018-10-10 16-44-37](https://user-images.githubusercontent.com/9090674/46748601-d2a06100-ccab-11e8-8468-c3c0befc7675.png)

The correct form should be:
![screenshot from 2018-10-10 16-42-18](https://user-images.githubusercontent.com/9090674/46748566-bbfa0a00-ccab-11e8-86b5-9f6b57c678c5.png)

---
I'd like to help you by fixing this issue, is it okay to load a JS file that checks the current URL, if it's Arabic, Farsi or Hebrew,  it applies the `direction: rtl` property to the template, with some exceptions (English content...). 

Or is there a better solution?

**Comment by freakboy3742** [comment]
Looks like this has been addressed by the Arabic translation.
