### ISSUE TITLE
Translation to Russian

### ISSUE THREAD

**Issue by Flynn84** [beeware/beeware.github.io#326]
Hello! I'd like to start translating https://pybee.org to Russian.

Now working on the main page. 

P.S. Really interested in Python. Found your project reading an answer on the SO yesterday. Before that only heard of Kivy as a framework for mobile development.

**Comment by freakboy3742** [comment]
Closing due to a lack of activity. If anyone is interested in submitting a Russian (or any other translation), we don't need a ticket; submitting only the PR for the translation update is fine.
