### ISSUE TITLE
Wrongly named list item in language selection dropdown on website

### ISSUE THREAD

**Issue by SashwatAnagolum** [beeware/beeware.github.io#331]
I spotted a bug in the BeeWare site that shows when users try to change the language option - a 'None' option exists in the language list - this should be changed to Danish. See the screenshot below:

![image](https://user-images.githubusercontent.com/42544553/51422463-e164b100-1bd4-11e9-9954-d5587b623cd3.png)

**Comment by bmacer** [comment]
Created PR #347 to fix this.
