### ISSUE TITLE
Add preview capability for PR changes

### ISSUE THREAD

**Issue by freakboy3742** [beeware/beeware.github.io#393]
At present, if a user submits a PR, there's no way to validate that it renders correctly. 

We should add, as part of the PR test process, a rendering of the site that can be viewed and tested.

**Comment by goanpeca** [comment]
I can work on this @freakboy3742. Any specifics you had in mind? Like building the site and uploading some artifact? or ?

**Comment by freakboy3742** [comment]
"Build the site, upload somewhere visible" is the core of the idea. If someone submits a CSS, template, or configuration change, the review process currently involves pulling down the site, building it, checking the change, and then approving the PR. Most of that could be done automated.

Beyond that, I'm open to suggestions. Building in CI and uploading the result to an S3 bucket configured to serve as static content would be an obvious option. However, if there's another option out there (I've heard good things about Netlify, for example), I'm open to the suggestion. I'm even willing to move the main site hosting if that makes sense, and spend a small amount of money for monthly hosting if that makes sense.

**Comment by goanpeca** [comment]
Looking into netlify
