### ISSUE TITLE
setup.py commands not found

### ISSUE THREAD

**Issue by venomega** [beeware/beeware.github.io#453]
please what am i doing wrong
i just create a default project with 
    briefcase new
    cd helloworld
    briefcase create android
an it says
    Template does not support 3.9

and if i do
    cookiecutter https://github.com/pybee/briefcase-template
    cd helloworld
    python setup.py android -s
it says
````
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'android'
````
does not work for any command writed inside setup.py
**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - Operating System:
 - Python version:
 - Software versions:
   - Briefcase:
   - Toga:
   - ...

**Additional context**

**Comment by venomega** [comment]
im using archlinux, i have create an new rootfs an install everything inside that rootfs, i tried with venv too and does not work, say same errors

**Comment by freakboy3742** [comment]
After you ran `briefcase new`, you received an error message "Template does not support 3.9".

That's the cause of the problem. Briefcase requires binary components, and we haven't prepared those components for Python 3.9. If you use Python 3.8 or earlier, you won't get that error.

The subsequent error about "setup.py not found" is an error of usage; you've cloned an old version of the template, which didn't support Android.
