### ISSUE TITLE
The Contribute To Beeware Button is too thin in some breakpoints

### ISSUE THREAD

**Issue by pathunstrom** [beeware/beeware.github.io#559]
### Describe the bug

Between approximated 575 pixels wide and 995 pixels wide, the buttons in the main body get reduced to a width which cuts off the text of the "Contribute to Beeware" button.

### Steps to reproduce

1. Go to beeware.org
2. Resize viewport to between 575 pixels and 995 pixels.
3. Scroll down to Contribute!

### Expected behavior

The button should always be wide enough to read the contents.

### Screenshots

![image](https://github.com/beeware/beeware.github.io/assets/6393101/77a7f969-6ee8-48a7-8dee-78a208858b8a)

### Environment

- Operating System: Windows
- Python version: N/A
- Software versions:
  - Briefcase: N/A
  - Toga: N/A
  - Firefox: 124.0.2
  - Microsoft Edge: 123.0.2420.97
  - Safari 17.4.1

**Comment by freakboy3742** [comment]
I see the upper breakpoint limit at ~745 - but agreed this problem exists. Thanks for the report.
