### ISSUE TITLE
Layout Issues on Community Page Sideboard at mid-sized viewports

### ISSUE THREAD

**Issue by pathunstrom** [beeware/beeware.github.io#561]
### Describe the bug

The sidebar on the Community page overflows its box at mid size layouts.

### Steps to reproduce

1. Go to the [Community Page](https://beeware.org/community/)
2. Resize viewport between 767 pixels and 576 pixels.
3. View sidebar for error.

### Expected behavior

Don't want the headers to overflow the sidebar.

### Screenshots

![image](https://github.com/beeware/beeware.github.io/assets/6393101/e313a751-8ad3-417d-ab8e-86e2f978feab)

### Environment

* Firefox 124.0.2
* Edge 123.0.2420.97
* Safari 17.4.1

**Comment by tiidadavena** [comment]
I give it a look during the PyCon US 2024.

**Comment by tiidadavena** [comment]
> I give it a look during the PyCon US 2024.

I tried to assign the issue to me but it doesn't work :P but I work on it tho

**Comment by freakboy3742** [comment]
@tiidadavena We don't really use the "assign" mechanism, because it requires team membership permissions; dropping a comment is all we ask to "claim" an issue.

**Comment by tiidadavena** [comment]
> @tiidadavena We don't really use the "assign" mechanism, because it requires team membership permissions; dropping a comment is all we ask to "claim" an issue.

I see and ty for the explanation :D
