### ISSUE TITLE
Translation to pt_BR.

### ISSUE THREAD

**Issue by azengard** [beeware/beeware.github.io#63]
We can use this issue to organize the translation.
--------
I will translate the following pages:

**Work on**
http://pybee.org/community/team/
http://pybee.org/community/getting-help/

**Waiting for Commit**
http://pybee.org/community/behavior/
http://pybee.org/community/behavior/code-of-conduct/
http://pybee.org/community/behavior/making-a-coc-complaint/
http://pybee.org/community/behavior/changes/

**Done**
http://pybee.org/contact/
http://pybee.org/contact/media/
http://pybee.org/community/
http://pybee.org/contributing/membership/ - (incomplete)
http://pybee.org/contributing/challenge-coins/
http://pybee.org/contributing/core-team/
http://pybee.org/contributing/how/
http://pybee.org/contributing/
http://pybee.org/contributing/what/
http://pybee.org/contributing/first-time/ (and sub pages)

-------
There is also a pyladie doing the "Using GitHub" page. Yay \0/
http://pybee.org/contributing/first-time/github/

**Comment by rsip22** [comment]
I'm translating the homepage.

I'm also working on the links and navbar and fixing things site-wide to improve our translation effords.

**Comment by joncasdam** [comment]
hello.what is status on this? I can jump in too.

**Comment by freakboy3742** [comment]
@joncasdam Any page on the BeeWare site that doesn't have a `+pt_BR` version still requires translation. You can also review any of the existing pages to confirm the translation is accurate.

**Comment by joncasdam** [comment]
ok, @freakboy3742 - working on pages `project` folder.
PR coming soon.

**Comment by AltoRetrato** [comment]
Hi, everyone!

It seems that nobody has been working on the Portuguese translations for quite some time. I'll try to do a bit each day, when I find some free time.

BTW, there are plenty of "Crowdsourced Translations Managers" that are free for OSS, such as [POEditor](https://poeditor.com/), [Transifex](https://www.transifex.com/), [OneSky](https://www.oneskyapp.com), [Crowdin](https://crowdin.com), [Zanata](http://zanata.org), [Launchpad](https://translations.launchpad.net), and more. They are usually pretty good to manage both software and website translations, with their own revision features (some down even to single strings). IMHO, they are much better than GitHub to work with multiple languages translations...

**Comment by goanpeca** [comment]
I had some discussion of options and how django girls tutorial is setup wth crowdin (https://crowdin.com/) 

https://github.com/DjangoGirls/tutorial/issues/1271

It would require setting up a "bot account" and some additional scripts, but could help in the translation process.

**Comment by freakboy3742** [comment]
@goanpeca FWIW - we already have a bot account with repo modification permissions (@brutusthebee) - if we need another one specifically for translations, that's no problem either. 

I'll have a read and poke around crowdin and see what is involved.

**Comment by goanpeca** [comment]
I think crowdin gives foss to accounts not orgs and that is why we need a bot so the bot has a fork of the website and is linked to that repo.

**Comment by AltoRetrato** [comment]
@freakboy3742 From this group, Crowdin was my favorite: very fast, easy to use and with great features, and a real joy to use. It supports many import / export formats, and have a nice [API](https://support.crowdin.com/api/api-integration-setup/).

As you might have already seen, the [Open Source project setup request form](https://crowdin.com/page/open-source-project-setup-request) must be filled / submitted by the project lead.

**Comment by goanpeca** [comment]
It is worth noting that we will be still useing `.lr` files, which is not the same as plain `.rst` or `.md` for which those platforms might be better suited.

**Comment by AltoRetrato** [comment]
Crowdin currently supports [30+ formats](https://support.crowdin.com/supported-formats/), and unsupported formats are treated as plain text files. It seems that .lr files could be used as-is (i.e., as .txt), or if someone is inclined to, a script could be written to automatically convert to/from a supported format during import/export.

**Comment by goanpeca** [comment]
@AltoRetrato yes, what I am saying is that the lektor format is more susceptible to corruption if the user accidentally changes a key or removes a `--` in a section separating contents,

**Comment by AltoRetrato** [comment]
True - but that also goes for the current state of the translations, right?

Another option would be to use a different format and convert to/from it, but I don't know the Lektor file structure/requirements, so I have no idea if a simple conversion to/from, e.g., JSON, would suffice.

**Comment by goanpeca** [comment]
>True - but that also goes for the current state of the translations, right?

No, cause they are PRs that can be reviewed, and run tests. 

>Another option would be to use a different format and convert to/from it, but I don't know the Lektor file structure/requirements, so I have no idea if a simple conversion to/from, e.g., JSON, would suffice.

I don't think this is worth it

**Comment by goanpeca** [comment]
However there is a lektor feature in progress that would allow embedding files as the content of a filed, so for long content, we can have a separate file that is purely md or purely rst.

**Comment by AltoRetrato** [comment]
>> True - but that also goes for the current state of the translations, right?

> No, cause they are PRs that can be reviewed, and run tests.

The same process could be applied via Crowdin, too: after a batch of translations are done, a script would be invoked to download the .lr files from Crowdin, run automatic tests and make a pull request for each one that pass.

**Comment by freakboy3742** [comment]
Closing due to a lack of activity. If anyone is interested in submitting a Brazilian (or any other translation), we don't need a ticket; submitting only the PR for the translation update is fine.

**Comment by AltoRetrato** [comment]
> Closing due to a lack of activity. If anyone is interested in submitting a Brazilian (or any other translation), we don't need a ticket; submitting only the PR for the translation update is fine.

IIRC, I sent a few PRs that required local testing with Lektor (and screenshots to prove it), so they were never approved...

**Comment by freakboy3742** [comment]
@AltoRetrato Apologies for that - we definitely don't want the efforts of contributors to be wasted.

I've recorded #393 as a possible fix that will (hopefully) prevent others having the same experience.
